FROM wordpress:5.4.1-php7.3-apache

COPY dist/themes /var/www/html/wp-content/themes
VOLUME /var/www/html/wp-content/themes
COPY dist/plugins /var/www/html/wp-content/plugins
VOLUME /var/www/html/wp-content/plugins
